package com.smarttours.atlasguidebackend.domain.user.output;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * Represents the entire personalized trip plan generated by the AI.
 * This is the root object for JSON parsing.
 */
public class ItineraryPlan {

    @JsonProperty("trip_summary")
    private String tripSummary;

    @JsonProperty("itinerary")
    private List<DayPlan> itinerary;

    // Constructors
    public ItineraryPlan() {}

    public ItineraryPlan(String tripSummary, List<DayPlan> itinerary) {
        this.tripSummary = tripSummary;
        this.itinerary = itinerary;
    }

    // Getters and Setters
    public String getTripSummary() {
        return tripSummary;
    }

    public void setTripSummary(String tripSummary) {
        this.tripSummary = tripSummary;
    }

    public List<DayPlan> getItinerary() {
        return itinerary;
    }

    public void setItinerary(List<DayPlan> itinerary) {
        this.itinerary = itinerary;
    }
}