package com.smarttours.atlasguidebackend.domain.user.output;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.smarttours.atlasguidebackend.domain.exceptions.UncompleteItineraryException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.util.CollectionUtils;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * Represents the entire personalized trip plan generated by the AI.
 * This is the root object for JSON parsing.
 */
public class ItineraryPlan {

    private static final Logger LOG = LoggerFactory.getLogger(ItineraryPlan.class);

    @JsonProperty(value = "trip_id")
    private String tripId;

    @JsonProperty(value = "trip_title")
    private String tripTitle;

    @JsonProperty(value = "destination")
    private String destination;

    @JsonProperty(value = "start_date")
    private String startDate;

    @JsonProperty(value = "trip_duration")
    private int tripDuration;

    @JsonProperty(value = "is_saved")
    private boolean isSaved;

    @JsonProperty(value = "trip_summary", required = true)
    private String tripSummary;

    @JsonProperty(required = true, value = "itinerary")
    private List<DayPlan> itinerary;

    // Constructors
    public ItineraryPlan() {}

    public ItineraryPlan(String tripSummary, List<DayPlan> itinerary) {
        this.tripSummary = tripSummary;
        this.itinerary = itinerary;
    }

    // Getters and Setters
    public String getTripId() { return tripId; }
    public void setTripId(String tripId) { this.tripId = tripId; }

    public String getTripTitle() { return tripTitle; }
    public void setTripTitle(String tripTitle) { this.tripTitle = tripTitle; }

    public String getDestination() { return destination; }
    public void setDestination(String destination) { this.destination = destination; }

    public String getStartDate() { return startDate; }
    public void setStartDate(String startDate) { this.startDate = startDate; }

    public int getTripDuration() { return tripDuration; }
    public void setTripDuration(int tripDuration) { this.tripDuration = tripDuration; }

    public boolean isSaved() { return isSaved; }
    public void setSaved(boolean saved) { isSaved = saved; }

    public String getTripSummary() {
        return tripSummary;
    }

    public void setTripSummary(String tripSummary) {
        this.tripSummary = tripSummary;
    }

    public List<DayPlan> getItinerary() {
        return itinerary;
    }

    public void setItinerary(List<DayPlan> itinerary) {
        this.itinerary = itinerary;
    }

    /**
     * Validates if the ItineraryPlan contains at least one DayPlan and each DayPlan contains at least one Event.
     * @return
     * @throws UncompleteItineraryException
     */
    public void isComplete() throws UncompleteItineraryException {
        AtomicBoolean complete = new AtomicBoolean(true);
        List<DayPlan> DayPlanList = this.getItinerary();
        if(CollectionUtils.isEmpty(DayPlanList)) {
            LOG.error("ItineraryPlan must contain at least one DayPlan");
            complete.set(false);
            throw new UncompleteItineraryException("ItineraryPlan must contain at least one DayPlan.");
        }
        DayPlanList.forEach(dayPlan ->
                {
                    if(CollectionUtils.isEmpty(dayPlan.getEvents())) {
                        LOG.error("DayPlan {} must contain at least one Event", dayPlan.getDay());
                        complete.set(false);
                    }
                }
        );
        if(!complete.get()) {
            throw new UncompleteItineraryException("ItineraryPlan is incomplete. See logs for details.");
        };
    }

    @Override
    public String toString() {
        return "ItineraryPlan{" +
                "tripSummary='" + tripSummary + '\'' +
                ", itinerary=" + itinerary +
                '}';
    }
}