spring:
  application:
    name: atlas-guide-backend
  profiles:
    active: ollama,debug
  virtual-thread:
    enabled: true
  config:
    import: optional:vault://kv-tours/backend/${environment}/ai-config,optional:vault://kv-tours/backend/${environment}/database,optional:vault://kv-tours/backend/${environment}/auth
  ai:
    chat:
      client:
        enabled: false
  # Datasource configuration
  datasource:
    url: ${DB_URL}
    username: ${APP_DB_USER}
    password: ${APP_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: ${show_sql:false}
    hibernate:
      ddl-auto: ${ddl-auto:update} # Use 'update' or 'validate' in production
    properties:
      hibernate:
        format_sql: ${format_sql:false}
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: ${batch_size:50}
        batch_versioned_data: true
  security:
    oauth2:
      resourceserver:
        jwt:
#          audiences: tours-advisor-mobile
          audiences: account
          issuer-uri: http://localhost:8080/realms/tours-advisor
#          jwk-set-uri: http://localhost:8080/realms/tours-advisor/protocol/openid-connect/certs
#      client:
#        registration:
#          keycloak:
#            client-id: tours-advisor-backend
#            client-secret: YOUR_CLIENT_SECRET_FROM_KEYCLOAK
#            authorization-grant-type: client_credentials
#            scope: openid, profile, email
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8080/realms/tours-advisor
  cloud:
    vault:
      scheme: http
      kv:
        enabled: true
      uri: ${VAULT_URI:http://localhost:8200}
      authentication: APPROLE
      app-role:
        role-id: ${VAULT_ROLE_ID}
        secret-id: ${VAULT_SECRET_ID}


springdoc:
  swagger-ui:
    oauth-config:
      authorization-url: http://localhost:8080/realms/tours-advisor/protocol/openid-connect/auth
      token-url: http://localhost:8080/realms/tours-advisor/protocol/openid-connect/token
#      client-id: tours-advisor-mobile
#      client-secret: KavZ0H3JkuvBa42bZsCqLWRDIwwmzD3W
    oauth:
      authorization-url: http://localhost:8080/realms/tours-advisor/protocol/openid-connect/auth
      token-url: http://localhost:8080/realms/tours-advisor/protocol/openid-connect/token
      clientId: tours-advisor-mobile
      clientSecret: KavZ0H3JkuvBa42bZsCqLWRDIwwmzD3W

server:
  port: ${SERVER_PORT:8090}
#  servlet:
#    context-path: /api
#springdoc:
#  swagger-ui:
#    path: /swagger-ui/home.html