package com.smarttours.atlasguidebackend.infrastructure.entities;

import jakarta.persistence.*;

import java.util.List;

/**
 * Represents the entire personalized trip plan generated by the AI.
 * This is the root object for JSON parsing.
 */
@Entity
@Table(name = "itinerary_plans")
public class ItineraryPlanEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "itinerary_plan_seq")
    @SequenceGenerator(name = "itinerary_plan_seq", sequenceName = "itinerary_plan_seq", allocationSize = 50)
    private Long id;

    private String tripId;

    private String tripTitle;

    private String destination;

    private String startDate;

    @Column(nullable = false, columnDefinition = "integer not null default -1")
    private int tripDuration;

    @Column(columnDefinition = "TEXT")
    private String tripSummary;

    @OneToMany(mappedBy = "itineraryPlan",
            cascade = {CascadeType.PERSIST, CascadeType.MERGE},
            fetch = FetchType.LAZY,
            orphanRemoval = true)
    private List<DayPlanEntity> dayPlans;

    // Constructors
    public ItineraryPlanEntity() {}

    // Getters and Setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getTripId() { return tripId; }
    public void setTripId(String tripId) { this.tripId = tripId; }

    public String getTripTitle() { return tripTitle; }
    public void setTripTitle(String tripTitle) { this.tripTitle = tripTitle; }

    public String getDestination() { return destination; }
    public void setDestination(String destination) { this.destination = destination; }

    public String getStartDate() { return startDate; }
    public void setStartDate(String startDate) { this.startDate = startDate; }

    public int getTripDuration() { return tripDuration; }
    public void setTripDuration(int tripDuration) { this.tripDuration = tripDuration; }

    public String getTripSummary() { return tripSummary; }
    public void setTripSummary(String tripSummary) { this.tripSummary = tripSummary; }

    public List<DayPlanEntity> getDayPlans() { return dayPlans; }
    public void setDayPlans(List<DayPlanEntity> dayPlans) { this.dayPlans = dayPlans; }
}