package com.smarttours.atlasguidebackend.infrastructure.entities;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;

import java.util.List;
import java.util.UUID;

/**
 * Represents the entire personalized trip plan generated by the AI.
 * This is the root object for JSON parsing.
 */
@Entity
@Table(name = "itinerary_plans")
public class ItineraryPlanEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    private String tripSummary;

    @OneToMany(cascade = CascadeType.PERSIST, fetch = FetchType.LAZY)
    private List<DayPlanEntity> itinerary;

    // Constructors
    public ItineraryPlanEntity() {}

    public ItineraryPlanEntity(String tripSummary, List<DayPlanEntity> itinerary) {
        this.tripSummary = tripSummary;
        this.itinerary = itinerary;
    }

    // Getters and Setters
    public String getTripSummary() {
        return tripSummary;
    }

    public void setTripSummary(String tripSummary) {
        this.tripSummary = tripSummary;
    }

    public List<DayPlanEntity> getItinerary() {
        return itinerary;
    }

    public void setItinerary(List<DayPlanEntity> itinerary) {
        this.itinerary = itinerary;
    }

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }
}