package com.smarttours.atlasguidebackend.infrastructure.entities;

import jakarta.persistence.*;

import java.util.List;

/**
 * Represents the entire personalized trip plan generated by the AI.
 * This is the root object for JSON parsing.
 */
@Entity
@Table(name = "itinerary_plans")
public class ItineraryPlanEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;

    @Lob
    private String tripSummary;

    @OneToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}
            , fetch = FetchType.LAZY)
    private List<DayPlanEntity> dayPlans;

    // Constructors
    public ItineraryPlanEntity() {}

    public ItineraryPlanEntity(String tripSummary, List<DayPlanEntity> dayPlans) {
        this.tripSummary = tripSummary;
        this.dayPlans = dayPlans;
    }

    // Getters and Setters
    public String getTripSummary() {
        return tripSummary;
    }

    public void setTripSummary(String tripSummary) {
        this.tripSummary = tripSummary;
    }

    public List<DayPlanEntity> getDayPlans() {
        return dayPlans;
    }

    public void setDayPlans(List<DayPlanEntity> dayPlans) {
        this.dayPlans = dayPlans;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
}